INFO 2022-09-12 07:29:17,370 - Start time: 20220912T072917
WARNING 2022-09-12 07:29:31,819 - Exception encountered in fetch_trial_data. Traceback: Traceback (most recent call last):
  File "/global/cscratch1/sd/yazbeck/boa/boa/metaclasses.py", line 19, in wrapper
    return func(*args, **kwargs)
  File "/global/cscratch1/sd/yazbeck/boa/boa/wrapper_utils.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/elm_wrapper.py", line 431, in fetch_trial_data
    y_pred, y_true = get_model_obs(
  File "/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/elm_wrapper.py", line 274, in get_model_obs
    modeldf["CH4_SURF_AERE_TOT"] = np.multiply(AllModelVar[:,0],AllModelVar[:,2])+np.multiply(AllModelVar[:,1],(1-AllModelVar[:,2]))
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

